../../modules/jtframe/hdl/jtframe_uart.v
../../modules/jtframe/hdl/cpu/jtframe_z80.v
../../modules/jtframe/hdl/ram/jtframe_prom.v
../../modules/jtframe/hdl/ram/jtframe_ram.v
../../modules/jtframe/hdl/sdram/jtframe_rom.v
../../modules/jtframe/hdl/sdram/jtframe_romrq.v
../../modules/jtframe/hdl/jtframe_sh.v
../../modules/jtframe/hdl/clocking/jtframe_frac_cen.v
../../hdl/jtpopeye_dip.v
../../hdl/jtpopeye_bram.v
../../hdl/jtpopeye_security.v
../../hdl/jtpopeye_timing.v
../../hdl/jtpopeye_main.v
../../hdl/jtpopeye_bck.v
../../hdl/jtpopeye_buf.v
../../hdl/jtpopeye_colmix.v
../../hdl/jtpopeye_dma.v
../../hdl/jtpopeye_video.v
../../hdl/jtpopeye_video_dec.v
../../hdl/jtpopeye_obj.v
../../hdl/jtpopeye_objrom.v
../../hdl/jtpopeye_txt.v
../../hdl/jtpopeye_game.v
../../hdl/jtpopeye_prom_we.v
../../hdl/jtpopeye_roh_model.v
